name: be_safe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.0

  # Networking & API Calls
  http: ^1.3.0
  web_socket_channel: ^3.0.2

  # Firebase Services (For Push Notifications)
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

  # Authentication & JWT Handling
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1

  # UI & Styling
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  animations: ^2.0.11

  # Geolocation & Maps
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_maps_flutter: ^2.5.0

  # Permissions
  permission_handler: ^11.0.1
  contacts_service: ^0.6.3

  camera: ^0.11.0+2      # For video recording
  flutter_sound: ^9.2.13  # For audio recording
  path_provider: ^2.1.2   # For saving files locally
  mime: ^2.0.0

  # Background Services
  flutter_background_service: ^5.0.5
  workmanager: ^0.5.2
  vibration: ^3.1.3

  # Icons
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8

  # Notifications
  flutter_local_notifications: ^18.0.1

  http_parser: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
